#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017


#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1


#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: '*.nupkg'
    name: NuGet
