#---------------------------------#
#           environment           #
#---------------------------------#
image: Visual Studio 2017

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))


#---------------------------------#
#              build              #
#---------------------------------#
build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1


#---------------------------------#
#              tests              #
#---------------------------------#
test:
  assemblies: '**\bin\Release\*Test.dll'
  categories:
    except:
      - Manual


#---------------------------------#
#             artifacts           #
#---------------------------------#
artifacts:
  - path: '*.nupkg'
    name: NuGet


#---------------------------------#
#            on finish            #
#---------------------------------#
on_finish:
  - ps: Get-ChildItem -Path Failed_*.png -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }


#---------------------------------#
#              deploy             #
#---------------------------------#
deploy:
  provider: NuGet
  api_key:
    secure: iw4U6OpEAxeZY5bNxWxK4RC+S2Jj6pvtLLyJ0b+YxpaZPoQbCAFZOXv9rfkzG109
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
