#---------------------------------#
#           environment           #
#---------------------------------#
image: Visual Studio 2017

environment:
  nuget-api-key:
    secure: bqvXEmg4DmMbqRLDuBAYpe1iFgrlv0LmvQuYZ9DEtsdJqRStvMVgpVGQi6vPskCxK/tvUPVv/sLwzBu/osnAIg==

install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt .\nuget-api-key.enc -secret %nuget-api-key%


#---------------------------------#
#              build              #
#---------------------------------#
build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1


#---------------------------------#
#              tests              #
#---------------------------------#
test: off


#---------------------------------#
#             artifacts           #
#---------------------------------#
artifacts:
  - path: '*.nupkg'
    name: NuGet


#---------------------------------#
#              deploy             #
#---------------------------------#
deploy:
  provider: NuGet
  api_key:
    secure: w03iihR+NLHSJiP8NBsL0uGT8BEvjPUFOQok69hVhHARvwYpc0pCyV2UnjNiJSC7
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
