#---------------------------------#
#           environment           #
#---------------------------------#
image: Visual Studio 2019

install:
  - ps: |
      $logo = (Invoke-WebRequest "https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.raw").toString()
      Write-Host "$logo" -ForegroundColor Green


#---------------------------------#
#              build              #
#---------------------------------#
build_script:
  - cmd: PowerShell -Version 2.0 .\build\build.ps1 -Script .\build\build.cake


#---------------------------------#
#              tests              #
#---------------------------------#
test:
  assemblies: '**\bin\Release\*Test.dll'
  categories:
    except:
      - Manual


#---------------------------------#
#             artifacts           #
#---------------------------------#
artifacts:
  - path: '*.*nupkg'
    name: NuGet
    type: NuGetPackage


#---------------------------------#
#              deploy             #
#---------------------------------#
deploy:
  - provider: GitHub
    tag: ${APPVEYOR_REPO_TAG_NAME}
    release: Release ${APPVEYOR_REPO_TAG_NAME}
    description: TODO
    auth_token:
      secure: de2wnJZf6k7NY0XriDpf9BkrQ4MR5ZfDDWMM+H/K4OK3w0GpuJAMRj5PrO6tKu0K
    artifact: NuGet
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
    api_key:
      secure: iw4U6OpEAxeZY5bNxWxK4RC+S2Jj6pvtLLyJ0b+YxpaZPoQbCAFZOXv9rfkzG109
    symbol_server: https://www.nuget.org
    skip_symbols: false
    on:
      APPVEYOR_REPO_TAG: true
